routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('index');
// });

Route::get('/', 'IndexController@index');
Route::get('/jadwal-ukm', 'IndexController@jadwal');

// Route::get('/jadwal-ukm', function () {
//     return view('jadwal');
// });

Route::get('/user', function () {
    return view('user');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// });
Route::get('/dashboard', 'ProfileController@index');

Route::get('/login', 'LoginController@index');
Route::post("/login", 'LoginController@login');
Route::get('/logout', 'LoginController@logout');

Route::resource('ketuamhs', 'KetuamhsController');
Route::resource('pelatih', 'PelatihController');
Route::resource('adminkeuangan', 'AdminkeuanganController');
Route::resource('adminaplikasi', 'AdminaplikasiController');
Route::resource('pembina', 'PembinaController');
Route::resource('wk', 'WkController');

Route::resource('ukm', 'UkmController');
Route::resource('jadwal', 'JadwalController');
Route::resource('kegiatan', 'KegiatanController');
Route::get('kegiatan/showperukm/{kegiatan}', 'KegiatanController@showperukm')->name('kegiatan.showperukm');
Route::get('/kegiatan/createperukm/{kegiatan}', 'KegiatanController@createperukm');
Route::resource('laporan', 'LaporanController');
Route::resource('profile', 'ProfileController');
Route::resource('pengumuman', 'PengumumanController');
Route::get('pengumuman/showperukm/{pengumuman}', 'PengumumanController@showperukm');
Route::get('/pengumuman/createperukm/{pengumuman}', 'PengumumanController@createperukm');
Route::resource('absensi', 'AbsensiController');
Route::get('/absensi/create/{absensi}', 'AbsensiController@create');
Route::post('inputabsensi', 'AbsensiController@inputabsensi');
// Route::get('/absensi/detail/{absensi}', 'AbsensiController@detail')->name('absensi.detail');
Route::resource('anggota', 'AnggotaController');
Route::get('/anggota/create/{anggota}', 'AnggotaController@create');
Route::get('/anggota/{anggota}/showall', 'AnggotaController@showall');

// Route::get('/ketuamhs', 'UsersController@index');
// Route::get('/ketuamhs/create', 'UsersController@create');
// Route::post('/ketuamhs', 'UsersController@store');
// Route::get('/ketuamhs/{ketuamhs}', 'ProfileController@show');

// Route::get('/absensi/detail/{absensi}', [
//     'uses' => 'AbsensiController@detail',
//     'as' => 'absensi.detail'
// ]);

app/Pelatih.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pelatih extends Model
{
    
    public $timestamps = false;
    protected $primaryKey = 'id';
    protected $table = 'pelatihview';

    public function ukm()
    {
        return $this->hasMany('App\Ukm', 'pelatih_id', 'id');
    }

    public function jadwal()
    {
        return $this->hasMany('App\Jadwal', 'pelatih_id', 'id');
    }
}

app/Http/Controllers/PelatihController.php
<?php

namespace App\Http\Controllers;

use App\Users;
use App\Profile;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;

class PelatihController extends Controller
{
    public function index() {
        $data['users']= DB::table('users')->select('id', 'user_name', 'nama')->where('role', '=', 'pelatih')->get();
        return view('pelatih.index',$data);
        
    }

    public function create() {
        return view('pelatih.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'nama'      => ['required'],
            'user_name'     => ['required'],
            'password'      => ['required'],
            'role'          => ['required']
        ]);
        
        $users = new Users;
        $users->nama = $request->nama;
        $users->user_name = $request->user_name;
        $users->role =$request->role;
        $users->password = Hash::make($request->password);

        Session::flash('add',$users->save());
        return redirect('/pelatih')->with('status', 'Data User Berhasil Ditambahkan!');
    }

    public function show($id)
    {
        $pelatih = Profile::where('user_id', $id)->first();
        return view('pelatih.show', compact('pelatih'));
    }

    public function edit($id)
    {
        return view('pelatih.edit',[
            'pelatih' => Users::find($id)
        ]);

    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'nama'      => ['required'],
            'user_name'     => ['required'],
        ]);
        $user = Users::find($id);
        $user->nama = $request->nama;
        $user->user_name = $request->user_name;
        $user->password = Hash::make($request->password);

        Session::flash('edit',$user->save());
        return redirect()->route('pelatih.index')->with('status','Data User Berhasil Diubah');

    }

    public function destroy($id){
        Users::find($id)->delete();
        return redirect()->route('pelatih.index')->with('status','Data User Berhasil Dihapus');
    }
}

resources/views/pelatih/create.blade.php
@extends('layouts.mainadv')

@section('title', 'Tambah Data Pelatih')

@section('content')
<div class="container">
    <div class="col-lg-7">
        <div class="card shadow m-4">

            <div class="card-header py-3">
                <h3 class="mt-2">Tambah Data Pelatih</h3>
            </div>

            <div class="card-body p-2 m-2">
                <div class="row">
                    <div class="container">

                        <form method="post" action="{{ route('pelatih.store') }}">
                            @csrf
                            <div class="form-group mt-3">
                                <label for="nama">Nama Pelatih</label>
                                <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" id="nama" value="{{ old('nama') }}">
                                @error('nama')<div class="invalid-feedback">{{ $message }}</div>@enderror
                            </div>

                            <div class="form-group mt-3">
                                <label for="user_name">Username</label>
                                <input type="text" class="form-control @error('user_name') is-invalid @enderror" name="user_name" id="user_name" value="{{ old('user_name') }}">
                                @error('user_name')<div class="invalid-feedback">{{ $message }}</div>@enderror
                            </div>

                            <div class="form-group mt-3">
                                <label for="password">Password</label>
                                <input type="password" class="form-control @error('password') is-invalid @enderror" name="password" id="password" value="{{ old('password') }}">
                                @error('password')<div class="invalid-feedback">{{ $message }}</div>@enderror
                            </div>

                            <div class="form-group mt-3">
                                <label for="role">Role</label>
                                <select name="role" id="role" class="form-control @error('role') is-invalid @enderror">
                                    <option value="pelatih">Pelatih</option>
                                </select>
                                @error('role')<div class="invalid-feedback">{{ $message }}</div>@enderror
                            </div>

                            <button type="submit" class="btn btn-success btn-block border pt-2">Tambah Data</button>
                            <a href="{{ route('pelatih.index') }}" class="btn btn-outline-secondary btn-block">Batal</a>
                        </form>
                        
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
@endsection

resources/views/pelatih/edit.blade.php
@extends('layouts.mainadv')

@section('title', 'Edit Data Pelatih')

@section('content')
<div class="container">
    <div class="col-lg-7">
        <div class="card shadow mb-4">

            <div class="card-header py-3">
                <h3 class="">Edit Data Pelatih</h3>
            </div>

            <div class="card-body p-2 m-2">
                <div class="row">
                    <div class="container">

                        <form method="post" action="{{ route('pelatih.update',['pelatih'=>$pelatih->id]) }}">
                            @method('put')
                            @csrf
                            <div class="form-group mt-3">
                                <label for="nama">Nama Pelatih</label>
                                <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" id="nama" value="{{ $pelatih->nama }}">
                                <div class="text-danger">{{ $errors->first('nama')}}</div>
                            </div>

                            <div class="form-group mt-3">
                                <label for="user_name">Username</label>
                                <input type="text" class="form-control @error('user_name') is-invalid @enderror" name="user_name" id="user_name" value="{{ $pelatih->user_name }}">
                                <div class="text-danger">{{ $errors->first('username')}}</div>
                            </div>
                            <div class="form-group mt-3">
                                <label for="password">Password</label>
                                <input type="password" class="form-control @error('password') is-invalid @enderror" name="password" id="password" value="">
                                <div class="text-danger">{{ $errors->first('password') ? "" : "Kosongkan password jika tidak ingin diubah!" }}</div>
                            </div>
                            <button type="submit" class="btn btn-success btn-block border pt-2">Edit Data</button>
                            <a href="/pelatih" class="btn btn-outline-secondary btn-block">Batal</a>
                        </form>

                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>
@endsection

resources/views/pelatih/index.blade.php
@extends('layouts.mainadv')

@section('title', 'MDP UKM | Pelatih')

@section('content')
    <div class="container">
        <h1 class="ml-3">Pelatih</h1>

        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif

        <div class="card shadow m-4">
            <div class="card-header py-3">
                <a href="/pelatih/create" class="btn btn-outline-secondary btn-flat">
                    <span class="text">Tambah Pelatih</span>
                </a>
            </div>
            <div class="card-body p-2 m-3">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Nama Pelatih</th>
                                <th>User Name</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($users as $pelatih)
                            <tr>
                                <td>{{ $pelatih->nama }}</td>
                                <td>{{ $pelatih->user_name }}</td>
                                <td>
                                    <a href="/pelatih/{{ $pelatih->id}}" class="btn btn-warning btn-sm"><i class="fas fa-info"></i></a>
                                    <a href="{{ route('pelatih.edit',['pelatih'=>$pelatih->id]) }}" class="btn btn-info btn-sm"><i class="fas fa-edit"></i></a>
                                    <form action="{{ route('pelatih.destroy',['pelatih'=>$pelatih->id]) }}" method="POST" class="d-inline">
                                        @method('delete')
                                        @csrf
                                        <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-trash-alt"></i></button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pelatih/show.blade.php
@extends('layouts.mainadv')

@section('title', 'Profil Pelatih')

@section('content')
    <div class="container">
        <h1 class="ml-3 mb-3">Profil Pelatih</h1>

        <div class="col-lg-7">
            <div class="card card-outline card-info m-3">
                <div class="card-header">
                    <div class="card-title">
                        @if (!empty($pelatih->user_id))
                            <strong>{{ $pelatih->users->nama}}</strong>
                        @else
                            <p class="card-text">Data profil belum diisi</p>
                        @endif
                    </div>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                          <i class="fas fa-minus"></i></button>
                    </div>
                </div>
                <div class="card-body">
                    @if (!empty($pelatih->user_id))
                        <p class="mb-0"><strong>Username</strong></p>
                        <p class="card-text">{{ $pelatih->users->user_name }}</p>
                        
                        <p class="mb-0"><strong>NIK/NPM</strong></p>
                        <p class="card-text">{{ $pelatih->niknpm }}</p>

                        <p class="mb-0"><strong>Email</strong></p>
                        <p class="card-text">{{ $pelatih->email }}</p>
                    
                        <p class="mb-0"><strong>Nomor HP</strong></p>
                        <p class="card-text">{{ $pelatih->nohp }}</p>

                        <p class="mb-0"><strong>Alamat</strong></p>
                        <p class="card-text">{{ $pelatih->alamat }}</p>                     
                    @endif
                    
                    <a href="/pelatih" class="card-link card-info">Kembali</a>
                </div>
            </div>

        </div>

    </div>
@endsection