routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('index');
// });

Route::get('/', 'IndexController@index');
Route::get('/jadwal-ukm', 'IndexController@jadwal');

// Route::get('/jadwal-ukm', function () {
//     return view('jadwal');
// });

Route::get('/user', function () {
    return view('user');
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// });
Route::get('/dashboard', 'ProfileController@index');

Route::get('/login', 'LoginController@index');
Route::post("/login", 'LoginController@login');
Route::get('/logout', 'LoginController@logout');

Route::resource('ketuamhs', 'KetuamhsController');
Route::resource('pelatih', 'PelatihController');
Route::resource('adminkeuangan', 'AdminkeuanganController');
Route::resource('adminaplikasi', 'AdminaplikasiController');
Route::resource('pembina', 'PembinaController');
Route::resource('wk', 'WkController');

Route::resource('ukm', 'UkmController');
Route::resource('jadwal', 'JadwalController');
Route::resource('kegiatan', 'KegiatanController');
Route::get('kegiatan/showperukm/{kegiatan}', 'KegiatanController@showperukm')->name('kegiatan.showperukm');
Route::get('/kegiatan/createperukm/{kegiatan}', 'KegiatanController@createperukm');
Route::resource('laporan', 'LaporanController');
Route::resource('profile', 'ProfileController');
Route::resource('pengumuman', 'PengumumanController');
Route::get('pengumuman/showperukm/{pengumuman}', 'PengumumanController@showperukm');
Route::get('/pengumuman/createperukm/{pengumuman}', 'PengumumanController@createperukm');
Route::resource('absensi', 'AbsensiController');
Route::get('/absensi/create/{absensi}', 'AbsensiController@create');
Route::post('inputabsensi', 'AbsensiController@inputabsensi');
// Route::get('/absensi/detail/{absensi}', 'AbsensiController@detail')->name('absensi.detail');
Route::resource('anggota', 'AnggotaController');
Route::get('/anggota/create/{anggota}', 'AnggotaController@create');
Route::get('/anggota/{anggota}/showall', 'AnggotaController@showall');

// Route::get('/ketuamhs', 'UsersController@index');
// Route::get('/ketuamhs/create', 'UsersController@create');
// Route::post('/ketuamhs', 'UsersController@store');
// Route::get('/ketuamhs/{ketuamhs}', 'ProfileController@show');

// Route::get('/absensi/detail/{absensi}', [
//     'uses' => 'AbsensiController@detail',
//     'as' => 'absensi.detail'
// ]);

app/Ukm.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ukm extends Model
{
    public $timestamps = false;
    protected $table = 'ukm';
    protected $primaryKey = 'id';
    protected $fillable = ['nama_ukm', 'pembina_id', 'pelatih_id', 'ketuamhs_id', 'status'];

    public function pelatih()
    {
        return $this->belongsTo('App\Pelatih', 'pelatih_id', 'id');
    }

    public function pembina()
    {
        return $this->belongsTo('App\Pembina', 'pembina_id', 'id');
    }

    public function ketuamhs()
    {
        return $this->belongsTo('App\Ketuamhs', 'ketuamhs_id', 'id');
    }

    public function jadwal()
    {
        return $this->hasMany('App\Jadwal', 'ukm_id', 'id');
    }

    public function kegiatan()
    {
        return $this->hasMany('App\Kegiatan', 'ukm_id', 'id');
    }
    
    public function anggota()
    {
        return $this->hasMany('App\Anggota', 'ukm_id', 'id');
    }

    public function pengumuman()
    {
        return $this->hasMany('App\Pengumuman', 'ukm_id', 'id');
    }

    public function absensi()
    {
        return $this->hasMany('App\Absensi', 'ukm_id', 'id');
    }
}

app/Http/Controllers/UkmController.php
<?php

namespace App\Http\Controllers;

use App\Ukm;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;

class UkmController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (session('user')->role == 'adminaplikasi') 
        {
            $ukm = Ukm::all();
            return view('ukm.index', compact('ukm'));
        } 
        else if (session('user')->role == 'ketuamahasiswa') 
        {
            $id = session('user')->id;
            $ukm = Ukm::where('ketuamhs_id', $id)->get();
            return view('ukm.index', compact('ukm'));
        }
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $ukm = DB::select('select * from ukm');
        $pembina = DB::select('select * from pembinaview');
        $pelatih = DB::select('select * from pelatihview');
        $ketuamhs = DB::select('select * from ketuamhsview');
        return view('ukm.create', compact('ukm', 'pembina', 'pelatih', 'ketuamhs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_ukm'      => ['required'],
            'pembina_id'     => ['required'],
            'ketuamhs_id'      => ['required'],
            'status'          => ['required']
        ]);
        
        $ukm = new Ukm;
        $ukm->nama_ukm = $request->nama_ukm;
        $ukm->pembina_id = $request->pembina_id;
        $ukm->ketuamhs_id =$request->ketuamhs_id;
        $ukm->status = $request->status;

        //Ukm::create($request->all());
        Session::flash('add',$ukm->save());
        return redirect('/ukm')->with('status', 'Data UKM/HMJ Berhasil Ditambahkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Ukm  $ukm
     * @return \Illuminate\Http\Response
     */
    public function show(Ukm $ukm)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Ukm  $ukm
     * @return \Illuminate\Http\Response
     */
    public function edit(Ukm $ukm)
    {
        $pembina = DB::select('select * from pembinaview');
        $pelatih = DB::select('select * from pelatihview');
        $ketuamhs = DB::select('select * from ketuamhsview');
        return view('ukm.edit', compact('ukm', 'pembina', 'pelatih', 'ketuamhs'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Ukm  $ukm
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Ukm $ukm)
    {
        $request->validate([
            'nama_ukm' => 'required',
            'pembina_id' => 'required',
            'pelatih_id' => 'required',
            'ketuamhs_id' => 'required',
            'status' => 'required'
        ]);

        Ukm::where('id', $ukm->id)
                ->update([
                    'nama_ukm' => $request->nama_ukm,
                    'pembina_id' => $request->pembina_id,
                    'pelatih_id' => $request->pelatih_id,
                    'ketuamhs_id' => $request->ketuamhs_id,
                    'status' => $request->status
                ]);

        return redirect('/ukm')->with('status', 'Data UKM/HMJ berhasil diubah!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Ukm  $ukm
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ukm $ukm)
    {
        DB::table('ukm')->where('id',$ukm->id)->delete();
        return redirect('/ukm')->with('status', 'Data UKM/HMJ Berhasil Dihapus!');
    }
}

resources/views/ukm/create.blade.php
@extends('layouts.mainadv')

@section('title', 'Tambah Data UKM/HMJ')

@section('content')
<div class="container">
    <div class="col-lg-7">
        <div class="card shadow m-4">

            <div class="card-header py-3">
                <h3 class="mt-2">Tambah Data UKM/HMJ</h3>
            </div>

            <div class="card-body p-2 m-2">
                <div class="row">
                    <div class="container">

                        <form method="post" action="{{ route('ukm.store') }}">
                            @csrf
                            <div class="form-group mt-3">
                                <label for="nama_ukm">Nama UKM/HMJ</label>
                                <input type="text" class="form-control @error('nama_ukm') is-invalid @enderror" name="nama_ukm" id="nama_ukm" value="{{ old('nama_ukm') }}">
                                @error('nama_ukm')<div class="invalid-feedback">{{ $message }}</div>@enderror
                            </div>

                            <div class="form-group mt-3">
                                <label for="pembina_id">Nama Pembina</label>
                                <select name="pembina_id" id="pembina_id" class="form-control select2bs4 @error('pembina_id') is-invalid @enderror">
                                    @foreach ($pembina as $p)
                                        <option value="{{ $p->id }} {{ old('pembina_id') }}">{{ $p->nama }}</option>
                                    @endforeach
                                </select>
                                @error('pembina_id')<div class="invalid-feedback">{{ $message }}</div>@enderror
                            </div>

                            <div class="form-group mt-3">
                                <label for="pelatih_id">Nama Pelatih</label>
                                <select name="pelatih_id" id="pelatih_id" class="form-control select2bs4 @error('pelatih_id') is-invalid @enderror">
                                    <option value="">-</option>
                                    @foreach ($pelatih as $p)
                                        <option value="{{ $p->id }} {{ old('pelatih_id') }}">{{ $p->nama }}</option>
                                    @endforeach
                                </select>
                                @error('pelatih_id')<div class="invalid-feedback">{{ $message }}</div>@enderror
                            </div>

                            <div class="form-group mt-3">
                                <label for="ketuamhs_id">Nama Ketua Mahasiswa</label>
                                <select name="ketuamhs_id" id="ketuamhs_id" class="form-control select2bs4 @error('ketuamhs_id') is-invalid @enderror">
                                    @foreach ($ketuamhs as $k)
                                        <option value="{{ $k->id }} {{ old('ketuamhs_id') }}">{{ $k->nama }}</option>
                                    @endforeach
                                </select>
                                @error('ketuamhs_id')<div class="invalid-feedback">{{ $message }}</div>@enderror
                            </div>

                            <div class="form-group mt-3">
                                <label for="status">Status</label>
                                <select name="status" id="status" class="form-control @error('status') is-invalid @enderror">
                                    <option value="Aktif">Aktif</option>
                                    <option value="Non-aktif">Non Aktif</option>
                                </select>
                                @error('status')<div class="invalid-feedback">{{ $message }}</div>@enderror
                            </div>

                            <button type="submit" class="btn btn-success btn-block border pt-2">Tambah Data</button>
                            <a href="{{ route('ukm.index') }}" class="btn btn-outline-secondary btn-block">Batal</a>
                        </form>
                        
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
@endsection

resources/views/ukm/edit.blade.php
@extends('layouts.mainadv')

@section('title', 'Edit Data UKM')

@section('content')
<div class="container">
    <div class="col-lg-7">
        <div class="card shadow mb-4">

            <div class="card-header py-3">
                <h3 class="">Edit Data UKM</h3>
            </div>

            <div class="card-body p-2 m-2">
                <div class="row">
                    <div class="container">

                        <form method="post" action="{{ route('ukm.update',['ukm'=>$ukm->id]) }}">
                            @method('put')
                            @csrf
                            <div class="form-group mt-3">
                                <label for="nama_ukm">Nama UKM</label>
                                <input type="text" class="form-control @error('nama_ukm') is-invalid @enderror" name="nama_ukm" id="nama_ukm" value="{{ $ukm->nama_ukm }}">
                                <div class="text-danger">{{ $errors->first('nama_ukm')}}</div>
                            </div>

                            <div class="form-group mt-3">
                                <label for="pembina_id">Nama Pembina</label>
                                <select name="pembina_id" id="pembina_id" class="form-control select2bs4 @error('pembina_id') is-invalid @enderror">
                                    @foreach ($pembina as $p)
                                        <option value="{{ $p->id }}" {{ $ukm->pembina_id == $p->id ? 'selected' : ''}}>{{ $p->nama }}</option>
                                    @endforeach
                                </select>
                                @error('pembina_id')<div class="invalid-feedback">{{ $message }}</div>@enderror
                            </div>

                            <div class="form-group mt-3">
                                <label for="pelatih_id">Nama Pelatih</label>
                                <select name="pelatih_id" id="pelatih_id" class="form-control select2bs4 @error('pelatih_id') is-invalid @enderror">
                                    @foreach ($pelatih as $p)
                                        <option value="{{ $p->id }}" {{ $ukm->pelatih_id == $p->id ? 'selected' : ''}}>{{ $p->nama }}</option>
                                    @endforeach
                                </select>
                                @error('pelatih_id')<div class="invalid-feedback">{{ $message }}</div>@enderror
                            </div>

                            <div class="form-group mt-3">
                                <label for="ketuamhs_id">Nama Ketua Mahasiswa</label>
                                <select name="ketuamhs_id" id="ketuamhs_id" class="form-control select2bs4 @error('ketuamhs_id') is-invalid @enderror">
                                    @foreach ($ketuamhs as $k)
                                        <option value="{{ $k->id }}" {{ $ukm->ketuamhs_id == $k->id ? 'selected' : ''}}>{{ $k->nama }}</option>
                                    @endforeach
                                </select>
                                @error('ketuamhs_id')<div class="invalid-feedback">{{ $message }}</div>@enderror
                            </div>

                            <div class="form-group mt-3">
                                <label for="status">Status</label>
                                <select name="status" id="status" class="form-control @error('status') is-invalid @enderror">
                                    <option value="Aktif" {{ ($ukm->status == 'Aktif') ? 'selected' : '' }}>Aktif</option>
                                    <option value="Non-aktif" {{ ($ukm->status == 'Non-aktif') ? 'selected' : '' }}>Non Aktif</option>
                                </select>
                                <div class="text-danger">{{ $errors->first('status')}}</div>
                            </div>

                            <button type="submit" class="btn btn-success btn-block border pt-2">Edit Data</button>
                            <a href="/ukm" class="btn btn-outline-secondary btn-block">Batal</a>
                        </form>

                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>
@endsection

resources/views/ukm/index.blade.php
@extends('layouts.mainadv')

@section('title', 'SiMUDAH | UKM/HMJ')

@section('content')
    <div class="container">
        <h1 class="ml-3">UKM/HMJ</h1>

        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif

        <div class="card shadow m-4">
            @if (session('user')->role == 'adminaplikasi')
                <div class="card-header py-3">
                    <a href="{{ route('ukm.create') }}" class="btn btn-outline-secondary btn-flat">
                        <span class="text">Tambah UKM/HMJ</span>
                    </a>
                </div>    
            @else
                
            @endif
            
            <div class="card-body p-2 m-3">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Nama UKM/HMJ</th>
                                <th>Pembina</th>
                                <th>Pelatih</th>
                                <th>Ketua Mahasiswa</th>
                                <th>Status</th>
                                <th>Anggota</th>
                                @if (session('user')->role == 'adminaplikasi')
                                <th>Aksi</th>
                                @else
                                @endif
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($ukm as $u)
                            <tr>
                                <td>{{ $u->nama_ukm }}</td>
                                <td>{{ $u->pembina->nama }}</td>
                                @if (!empty($u->pelatih->nama))
                                    <td>{{ $u->pelatih->nama }}</td>
                                @else      
                                    <td>-</td>                          
                                @endif
                                <td>{{ $u->ketuamhs->nama }}</td>
                                <td>{{ $u->status }}</td>
                                <td>
                                    <center><a href="/anggota/{{ $u->id }}">Lihat</i></a></center>
                                </td>
                                @if (session('user')->role == 'adminaplikasi')
                                <td>
                                    <center>
                                    <a href="{{ route('ukm.edit',['ukm'=>$u->id]) }}" class="btn btn-info btn-sm"><i class="fas fa-edit"></i></a>
                                    <form action="{{ route('ukm.destroy',['ukm'=>$u->id]) }}" method="POST" class="d-inline">
                                        @method('delete')
                                        @csrf
                                        <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-trash-alt"></i></button>
                                    </form>
                                    </center>
                                </td>
                                @else
                                @endif
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection